# technical
device: cpu
# data
distance_threshold: 14.28
batch_size: 1
# training
lr: 0.002
epochs: 5 #15
weight_decay: 0.001
# model
input_dim: 40
hid_dim: 50 #320 #160
# output
num_classes: 14
# encoder implementation - 0 stands for vanilla version and 1 for custom version
n_graph_layers: 5
batch_norm: True
# conv_net implementation - 0-61
graph_conv_impl: 45
# fc_net implementation - 0 stands for vanilla version
classification_head_impl: 1