# technical
device: cpu
# data
distance_threshold: 14.28
batch_size: 1
node_batch_size: 512 # applicable only for batch_type = node
# training
lr: 0.002
epochs: 20
weight_decay: 0.0001
batch_type: graph # ['graph', 'node']
# model
input_dim: 40
hid_dim: 160
# output
num_classes: 14
# encoder implementation
n_graph_layers: 1
n_hidden_layers: 0
batch_norm: False
# conv_net implementation - ['GCNConv', 'SAGEConv', 'GraphConv', 'GatedGraphConv', 'ResGatedGraphConv', 'GATConv', 'GATv2Conv', 'TransformerConv', 'AGNNConv', 'TAGConv', 'ARMAConv', 'SGConv', 'MFConv', 'FeaStConv', 'HypergraphConv', 'LEConv', 'ClusterGCNConv', 'GENConv', 'FiLMConv', 'SuperGATConv']
graph_conv_impl: FiLMConv
# fc_net implementation - 0 stands for vanilla version
classification_head_impl: 0