# technical
device: cpu
# data
distance_threshold: 14.28
batch_size: 1
node_batch_size: 200 # applicable only for batch_type = node and neighbors
# training
lr: 0.001
epochs: 5
weight_decay: 0.0001
batch_type: neighbors # ['graph', 'node', 'neighbors']
# model
input_dim: 40
hid_dim: 160
# output
num_classes: 14
# encoder implementation
n_graph_layers: 1
batch_norm: False
# conv_net implementation - ['GCNConv', 'SAGEConv', 'GraphConv', 'GatedGraphConv', 'ResGatedGraphConv', 'GATConv', 'GATv2Conv', 'TransformerConv', 'AGNNConv', 'TAGConv', 'ARMAConv', 'SGConv', 'MFConv', 'FeaStConv', 'HypergraphConv', 'LEConv', 'ClusterGCNConv', 'GENConv', 'FiLMConv', 'SuperGATConv']
graph_conv_impl: FiLMConv
# fc_net implementation - 0 stands for vanilla version
classification_head_impl: 1